[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build && cd ../backend && npm install && cp prisma/schema.prod.prisma prisma/schema.prisma && npx prisma db push --accept-data-loss && npx prisma generate && node prisma/seed-prod.js"

[deploy]
startCommand = "cd backend && NODE_ENV=production node server.js"
healthcheckPath = "/api/questions?limit=1"
restartPolicyType = "on_failure"
